{% set name = "google-cloud-managedkafka" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/google_cloud_managedkafka-{{ version }}.tar.gz
  sha256: cc431c9082cceb4f6838c76f18302fed5d1c81a119ca0d5abfadd8d1001c66cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - google-api-core >=1.34.1,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0dev,!=2.24.0,!=2.25.0
    # use the more restrictive proto-plus version to stay noarch: python
    - proto-plus >=1.25.0,<2.0.0dev
    - protobuf >=3.20.2,<6.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google.cloud.managedkafka
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-managedkafka
  summary: Google Cloud Managedkafka API client library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-managedkafka
  doc_url: https://github.com/googleapis/google-cloud-python/blob/main/packages/google-cloud-managedkafka/README.rst

extra:
  recipe-maintainers:
    - xylar
