schema_version: 1

context:
  name: google-cloud-managedkafka
  version: 0.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/google_cloud_managedkafka-${{ version }}.tar.gz
  sha256: b35ef56c8b8bf9caedef5fd104d5405c0f3352695aee04e204dd50a599044016

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    # excluding python 3.14 for now because we don't have the required grpcio on conda-forge
    - python >=${{ python_min }},<3.14
    - google-api-core >=1.34.1,<3.0.0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0,!=2.24.0,!=2.25.0
    # using looser constraint because we can't support the python >=3.14 constraint
    - grpcio >=1.33.2,<2.0.0
    # use the more restrictive proto-plus version to stay noarch: python
    - proto-plus >=1.25.0,<2.0.0dev
    - protobuf >=3.20.2,<7.0.0,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

tests:
  - python:
      imports:
        - google.cloud.managedkafka
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Google Cloud Managedkafka API client library
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-managedkafka
  repository: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-managedkafka
  documentation: https://github.com/googleapis/google-cloud-python/blob/main/packages/google-cloud-managedkafka/README.rst

extra:
  recipe-maintainers:
    - xylar
